name: Workforce Portal Deploy PROD

on:
  push:
    tags:
      - prod

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@c514ae36604047560e33605b78f71804967bfb7a
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DESERT_0F5216903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "build"
          api_build_command: "npm run buildAndTest"
