# Workflow to build and deploy the workforce-portal Static Web App to the DEV environment.

name: Workforce Portal Deploy DEV
on:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!infra/**"
      - "!.github/workflows/**"
      - ".github/workflows/deploy-dev.yml"
      - ".github/workflows/deploy.yml"
      - "!.devcontainer/**"

  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: "${{ vars.AZURE_RESOURCE_GROUP_NAME_DEV }}${{ vars.AZURE_RESOURCE_UNIQUE_NAME_ELEMENT_DEV }}"

jobs:
  build-and-deploy-azure-swa-dev:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Find deployment token of the only SWA in resource group
        run: |
          webappname=$(az staticwebapp list --resource-group "${{ env.AZURE_RESOURCE_GROUP_NAME }}" --query '[0].name' --output tsv)
          deploymentToken=$(az staticwebapp secrets list --resource-group "${{ env.AZURE_RESOURCE_GROUP_NAME }}" --name "$webappname" --query 'properties.apiKey' --output tsv)
          echo "::add-mask::$deploymentToken"
          echo DEPLOYMENT_TOKEN=$deploymentToken >> $GITHUB_ENV

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@c514ae36604047560e33605b78f71804967bfb7a
        with:
          azure_static_web_apps_api_token: ${{ env.DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "build"
          api_build_command: "npm run buildAndTest"
