# Workflow to re-provision the azure resources to host/support the workforce-portal Static Web App DEV environment.

name: Workforce Portal Provision DEV
on:
  push:
    branches:
      - "main"
    paths:
      - "infra/**"
      - ".github/workflows/provision-dev.yml"

  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: "${{ vars.AZURE_RESOURCE_GROUP_NAME_DEV }}${{ vars.AZURE_RESOURCE_UNIQUE_NAME_ELEMENT_DEV }}"
  AZURE_RESOURCE_GROUP_LOCATION: "${{ vars.AZURE_RESOURCE_GROUP_LOCATION_DEV }}"
  AZURE_RESOURCE_UNIQUE_NAME_ELEMENT: "${{ vars.AZURE_RESOURCE_UNIQUE_NAME_ELEMENT_DEV }}"

jobs:
  provision-azure-resources-dev:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create resource group (if needed)
        run: |
          az group create --resource-group "${{ env.AZURE_RESOURCE_GROUP_NAME }}" --location "${{ env.AZURE_RESOURCE_GROUP_LOCATION }}"

      - name: Provision workforce-portal resources
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/workforce-portal.bicep
          parameters: >-
            environmentName=dev
            resourceUniqueNameElement="${{ env.AZURE_RESOURCE_UNIQUE_NAME_ELEMENT }}"
            b2cClientId="${{ secrets.B2C_CLIENT_ID_DEV }}"
            b2cClientSecret="${{ secrets.B2C_CLIENT_SECRET_DEV }}"
            b2cTenantId="${{ secrets.B2C_TENANT_ID_DEV }}"
            graphClientId="${{ secrets.GRAPH_CLIENT_ID_DEV }}"
            graphClientSecret="${{ secrets.GRAPH_CLIENT_SECRET_DEV }}"
            graphTenantId="${{ secrets.GRAPH_TENANT_ID_DEV }}"
            wfSharePointSite="${{ secrets.WF_SHAREPOINT_SITE_DEV }}"
            wfSharePointSiteHostname="${{ secrets.WF_SHAREPOINT_SITE_HOSTNAME_DEV }}"
            wfSharePointSitePath="${{ secrets.WF_SHAREPOINT_SITE_PATH_DEV }}"
            wfSpClientId="${{ secrets.WF_SHAREPOINT_CLIENT_ID_DEV }}"
            wfSpClientSecret="${{ secrets.WF_SHAREPOINT_CLIENT_SECRET_DEV }}"
            wfLoginsListGuid="${{ secrets.WF_LOGINS_LIST_GUID_DEV }}"
            wfProfilesListGuid="${{ secrets.WF_PROFILES_LIST_GUID_DEV }}"
            wfApplicationsListGuid="${{ secrets.WF_APPLICATIONS_LIST_GUID_DEV }}"
            wfTeamsListGuid="${{ secrets.WF_TEAMS_LIST_GUID_DEV }}"
            wfPhotosListGuid="${{ secrets.WF_PHOTOS_LIST_GUID_DEV }}"
            wfPhotosServerRelativeUrl="${{ secrets.WF_PHOTOS_SERVER_RELATIVE_URL_DEV }}"
            wfPhotosLibraryTitle="${{ secrets.WF_PHOTOS_LIBRARY_TITLE_DEV }}"
            wfMaxProfilePhotosPerPerson="${{ secrets.WF_MAX_PROFILE_PHOTOS_PER_PERSON_DEV }}"
            signUpSignInAuthority="${{ secrets.SIGN_UP_SIGN_IN_AUTHORITY_DEV }}"
            wfApiUrl="${{ secrets.WF_API_URL_DEV }}"
            wfApiClientAuthAuthority="${{ secrets.WF_API_CLIENT_AUTH_AUTHORITY_DEV }}"
            wfApiClientAuthClientId="${{ secrets.WF_API_CLIENT_AUTH_CLIENT_ID_DEV }}"
            wfApiClientAuthClientSecret="${{ secrets.WF_API_CLIENT_AUTH_CLIENT_SECRET_DEV }}"
            wfApiClientAuthScope="${{ secrets.WF_API_CLIENT_AUTH_SCOPE_DEV }}"
