# Workflow to re-provision the azure resources to host/support the workforce-portal Static Web App DEV environment.

name: Workforce Portal Provision DEV
on:
  push:
    branches:
      - "main"
    paths:
      - "infra/**"
      - ".github/workflows/provision-dev.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-azure-resources-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision base resources
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME_DEV }}
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/workforce-portal.bicep
          parameters: >-
            environmentName=dev
            resourceUniqueNameElement=31650
            repositoryUrl=${{ github.server_url }}/${{ github.repository }}
            repositoryToken=$${{ github.token }}
